from typing import Optional

from pydantic import BaseModel, Field


class QueryPlan(BaseModel):
    """
    Structured representation of the user's query.
    """

    intent: str

    author_name: Optional[str] = None

    channel_name: Optional[str] = None

    time_range: Optional[str] = None

    keywords: list[str] = Field(default_factory=list)

    aggregation: Optional[str] = None


class GeneratedQuery(BaseModel):
    """
    SQL query generated by the Query Engine.
    """

    sql: str