from typing import TypedDict, Literal

from app.query.query_plan import QueryPlan


class AgentState(TypedDict, total=False):

    # Original question from the user.
    question: str

    # Structured interpretation of the question.
    query_plan: QueryPlan

    # This will tell us whether to use both retrieval modes or just one
    retrieval_mode: Literal["both", "database_only", "semantic_only"]

    # SQL generated from the QueryPlan.
    sql_query: str

    # Results returned from PostgreSQL.
    database_results: list[dict]

    # Evidence retrieved through semantic search (chroma + postgresql).
    semantic_context: str

    # Combined evidence given to the answer generator.
    final_context: str

    # Final answer generated by the LLM.
    answer: str